<div id="send-new-message-form" class="container <?php echo $this->isVisible ? '' : 'd-none'; ?>">

    <div class="card shadow mb-4">
        <div class="card-header p-3">
            <div class="row">
                <div class="col">
                    <h4 class="mb-0">Send new message</h4>
                </div>
                <?php if (!$this->isVisible) : ?>
                    <div class="col">
                        <button type="button" id="btn-close-form" class="btn btn-sm btn-danger float-end">Close</button>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="card-body">
            <form action="" method="post">
                <div class="row mb-3">
                    <div class="col">
                        <label for="email" class="form-label">To</label>
                        <input type="email" class="form-control" name="email" id="email" required>
                    </div>
                    <div class="col">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" id="name" required>
                    </div>
                    <div class="col">
                        <label for="phone" class="form-label">Phone Number</label>
                        <input type="text" class="form-control" name="phone" id="phone" required>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="subject" class="form-label">Subject</label>
                    <input type="text" class="form-control" name="subject" id="subject" required>
                </div>

                <div class="mb-3">
                    <label for="message" class="form-label">Message</label>
                    <textarea name="message" id="message" class="form-control" cols="30" rows="10" required></textarea>
                </div>

                <div>
                    <button class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>