<div class="container">
    <div class="card shadow">
        <div class="card-header p-3">
            <div class="row">
                <div class="col">
                    <h4 class="mb-0 pt-1 align-middle">E-mails Sending Log</h4>
                </div>
                <div class="col-sm-2">
                    <button type="button" id="btn-open-form" class="btn btn-sm btn-primary float-end">New Message</button>
                </div>
            </div>
        </div>

        <div class="card-body">
            <table class="table table-sm table-striped table-bordered mb-0">
                <thead>
                    <tr class="border-top-0">
                        <th class="border-0">E-mail Address</th>
                        <th class="border-0">Full Name</th>
                        <th class="border-0" style="width: 140px;">Phone Number</th>
                        <th class="border-0 text-center" style="width: 100px;">Message</th>
                        <th class="border-0" style="width: 165px;">DateTime</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->logs as $log) : ?>
                        <tr>
                            <td><?php echo $log->email; ?></td>
                            <td><?php echo $log->name; ?></td>
                            <td><?php echo $log->phone_number; ?></td>
                            <td class="text-center">
                                <button type="button" class="show-details btn btn-link" data-email-id="<?php echo $log->id; ?>">Details</button>
                            </td>
                            <td><?php echo $log->datetime; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>