<div class="d-none">
    <div class="container">
        <div class="mb-3">
            <div class="mb-1"><strong>Name</strong></div>
            <div class="card">
                <div class="card-body p-2">
                    <?php echo $this->log->name; ?>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-1"><strong>E-mail</strong></div>
            <div class="card">
                <div class="card-body p-2">
                    <?php echo $this->log->email; ?>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-1"><strong>Phone Number</strong></div>
            <div class="card">
                <div class="card-body p-2">
                    <?php echo $this->log->phone_number; ?>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-1"><strong>Subject</strong></div>
            <div class="card">
                <div class="card-body p-2">
                    <?php echo $this->log->subject; ?>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-1"><strong>Message</strong></div>
            <div class="card">
                <div class="card-body p-2">
                    <?php echo $this->log->message; ?>
                </div>
            </div>
        </div>
    </div>
</div>